language: minimal
services:
  - docker
branches:
  only:
    - qa
    - production
    - DR-2564-production-travis
env:
  global:
    - AWS_DEFAULT_REGION=us-east-1
    - LOCAL_TAG_NAME=dc-frontend:$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER
    # DOCKER_LOGIN_PASSWORD
    - secure: "PWBKqzoehtHm6yDnQ85goSvBlnqE+N+DSesKtElIggKJGewGvHuSUWItYClBRIpbSPcm/5mn8yabhLPz37sJo7nJY/hJHQyGk8dwZtQcLBxVMSq4vMd6EbgeqZeT4oMWzQsT3TpLvESfSyEZu9MNzpKdFdxugOPKk0vUIDFTvBHpRtb+peptLqXBOXeo5czOJQta+QuQr3vd3PIUCYCoCGgx2ueoakIJXxpsNOe1/UHj97gbMlIypD+OdyCp3MQMn5etYFC/98HhTMGKrB8PI6qM/XdEzPzdw9zQjiDMq2xInQImgEFDymBwFfmIz8cEbjNiVnXxjnyfFgD5stmNHNi77rx2LF4MRlbEO7i9jZU7u1KfF+ruEnfYosZLgNKR+1JpeOr8Wvpe2yu/z7vMbeB9l1KvfGNLcRcA9M9kQigDwJJSCiIXj3d+KMoEy01Y5j8Nn18EOkEcOLSPrKBOsiH1y7zT/Ahnk17KIDkbPwiLyixwIjyhMRyVEp9FDjkBCrI93NZxYr3lyGaHSO8ZLHpi7v1NZcBxuNBlyhD+sHjkSdMZXaDBUJ73L7RVHCgdDYI2DP8PzbQ9yiM+6v2XTAbDHd6SMRW86+0K976i47mqAKKqWBLD1JuqYz01ZYTNVBR7UPkD3xS2elDlWeXJo7OKoZOgn2UrUvs4MlMY9Ko="
    # AWS_ACCESS_KEY_ID_QA, nypl-dams-dev 2023-12-29
    - secure: "sTrjgmIo5lRW45LkC6Ou/3vp6l6i5LQC83asS3XxnwGWBCi1mZ9Q20v2o372NAtcsqJxgUCfyNWlVsNOXVhapDRYi6s8oOvtN0pPl3Y/LGQ01qtLFvOuKkEtIsjasg5C/9k5WQHNDx8CLnJ1TU9oPT+8XQShaTZYWFhrSZQ/qyD1zCk7uYW/CsUh+AvXm4ktapIve9/bMjJTbTe45dtNa+1Y39VlQvbNnkKIjmncWH5qcVAuNocY0Lh1PINVnK/FhD8vhVsxwj4N5UAPn3peg6n3G/MMryT16Y51CsQwhZkQerFvWIz4U5H7TXn81UcwStyOL92R5MupEes7H9XHAe48GHeRBhnyuvsK/n1CBz4ck0b2JyTWkGBjgr41uAOEqTE2XsolBW6XCQQ4M8rrMf87S7K1VMXi1Vp8SqhP4Rlp2Wsyx1xl/nM7LtF0e+IR/uzxPsa7mLU9Jnj4ARCMwufTv+f60cxNZuZtT2A8kgvmiCbgMsCN5doqLRXE9qlgBrEDN8Xos8s0S0nUaWEehuwm7OXpq2KqekyaMRmPQcApWjfQXxlnXX5y1Lld7MSgsUa+OtxodWHtTOhG8hU8D/RBRbMRKm13sENwlKKFv54j9LjxwdEK9tYherIgGZwQHhc1Yb9CyqVkFi+dP9HXEUIMt9QHY48R+J/aLwxF+3s="
    # AWS_SECRET_ACCESS_KEY_QA, nypl-dams-dev 2023-12-29
    - secure: "PciR0AAEaOFZheL77pXENbsrevAFhtbb42FMrKB6hZgCbqkrJ9QoRGtd4JH3Ll557Qn2gWoYmWPC3gfO2TWcCTRRQ1VcgqFIqIKzM/D/Fj3Dhufv+PXsymGmP6bkU89LyEyWt5OxkkkhF0ZXuk/ucRF3mQHqVRGBINj6dQfSPKsZV7Eg9tZrTLP583Yk+n9+PEqRffeYJlZqPBrTkf5pJZgZ5vrk4d/dD+2Jzld66ETZttfGu1g7JfTx1fA8uSlOw7AnYB/2Wy+iFeMpvwju0WR5EU4BOa50CJS5abT8/Ujt3I0oMB/BM8hQtMZoq4dBtGJumbfALDdXhjO1IppbaJHES4fmJOtauErOtCWBk/VarAZ/aFV9/Eo3MlrIVmycD6QZDkCuAHqYTz1NCbtud5YEXOtFySyOXUbuxQ7l2kR8hDf4mjTAK8UaLyX7y3RIrWOwV651ivUGiIpJ7OyyDrWNxZIRj7TGQITT5MolqLBk8t5fuNivR1znqHoFEClAzqd2H/F3+pjUJvAi7+/PSIgjGDo90FHHnS0u7R1q/35MVlC8K5DX/NjJyUZCJB1LWE6Ver5EFjLbDI3WPy0DQh8URH70goO/XiWGkMhit6exmxFB4sDO0XpcZ+g67vv82doeBuCPd8ukc6wV2vZIfSc+y8KJXMY9eZ7NBiQu/lE="
    # AWS_ACCESS_KEY_ID_PRODUCTION, nypl-dams-prod 2023-12-29
    - secure: "AxFeC1wLt0j7Gu8Kh5h6KHMCbl2COq0CxZjKl/w+QLtTCZuqCB6DiIoFA9rlmf+2v3Ixt84rcnpcD6u2ABUqaF0O18MemeAXGhSovlHgGM9E74vivJWSv0oEiXP1mVe3P0cRgHqfZO5h40rAX48rMmQNlbh/BHAqftaEnFGGsvojjKPdwKycB1GeP9TSgsVzGQ95H5XcKMZGaC5mV5WaahEQLKYCaw81SO4OSQknIFzJP8bESIhyF+JAhN42L7biE4uA3eCCbhz+Schw7H7CKMgkdSI9GaPEl2BwP2sPrddfvAIJSdptJo9UIMVlELnsq87uensWpYq0NcnmktNQiEilkgUVGbJCuyLtkAffAXXqHPNA1oWCncfN6ix91ADoY241MAiI6OhyHtJmOby4xcUgUCoVlxnTWchHOO4ciqp/w2Wu/WEjetBMqicB+nsD8i+RT9ovVVjMiBD1GWTFe31psb57ObTIZpestUCEp/91gzggbedMbjJnMu/CAs3SVdOxFppeeP9bWTgJq3QYGqxeDehuDN+0Ax7QM25t/D2Bq7hTZIIKpFOp0Q8SpABva4UYVeR/O7/O0ihfvkeqM0FWfCrteya4PiHP79qX3Cxrd/HEH5wCKgF53p3TRkaES/TOisqm/bIlrkMWJ697Fx5XLvS1vUlvXiyOjo4lAeE="
    # AWS_SECRET_ACCESS_KEY_PRODUCTION, nypl-dams-prod 2023-12-29
    - secure: "UnlYqYBdutWVV00V03djajabghAg9ZpryG3cUYeBfTIrhzGitLmXzSUgLdUKMRe/dlevAHOdYQrmilKzMk/ldcJ4H7n0kXZ7LtQG89BRlUXTK+gZ3qHM0XHVB/LFQA0EFxn31uNGdJ3taEg3vwOA5DrV/iSbRJn86vpwt+4FuocAjU2rHpQWDvfX/CGmV6gLdzaRe2HVpumjnvEBr7KX/I4eKLTIiKtNAlBv09EorQGYFpiJUY3S+ii3KcE9gJZVm7A4IWSgc+O5lUhOnpS2OGZ/altxUJdFPWAtUfIQoDLUQAZRCIZm/ixzFr1azue0dCxDJr40JOmSCkqBnhIGNDvyO9OelaGM1wmG29IWNTxdbtTWl288P5Ni5hhfbhSKBgPA2IdAFa2HwX2czL+7/3aPzHoiNf1qvHOe2tS2XGsfdpWz29NKJ+4UVT2rqpL1mDBv4fOiT8Y1k3gQcMgHFu6xzGet/bdmLo8Xr/wC/O6D/PUTlCeAxXz9Cv3q4v37q8FLTSL1fOEuTFQROpHAqRV/sqPNNaobdRRZPjaA1mp96JoPEEHbqoLt82GSeTzYBFC8HagEdQvF+9YqEr+/ydTF9ysQbOcFNqZQX3q0/O5byd6JZzaFcZaq75HsT9vi911RR66GYPfMQGqZsNTBsSNCvXx0KCS9KraN4kg1ck4="
jobs:
  include:
    - stage: deploy QA
      if: (branch = qa) AND (type != pull_request)
      env:
        - ECR_URL=685731035297.dkr.ecr.us-east-1.amazonaws.com/dc-frontend:$TRAVIS_BRANCH-latest
        - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_QA
        - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_QA
        - CLUSTER_NAME=dc-frontend-qa
        - SERVICE_NAME=dc-frontend-qa
      install:
        - pip install --user awscli
      script:
        - eval $(aws ecr get-login --no-include-email)
        - docker build --tag "$LOCAL_TAG_NAME" .
        - docker tag "$LOCAL_TAG_NAME" "$ECR_URL";
        - docker push "$ECR_URL";
        - aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --force-new-deployment
    - stage: deploy production
      if: (branch = production) AND (type != pull_request)
      env:
        - ECR_URL=557492996044.dkr.ecr.us-east-1.amazonaws.com/dc-frontend:latest
        - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_PRODUCTION
        - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_PRODUCTION
        - CLUSTER_NAME=dc-frontend
        - SERVICE_NAME=dc-frontend
      install:
        - pip install --user awscli
      script:
        - eval $(aws ecr get-login --no-include-email)
        - docker build --tag "$LOCAL_TAG_NAME" .
        - docker tag "$LOCAL_TAG_NAME" "$ECR_URL";
        - docker push "$ECR_URL";
        - aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --force-new-deployment
