# For all pushes, this workflow will
#     - Install deps
#     - Lint
#     - Test
name: Test/Lint CI

on: push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Cache and install node modules
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false
      - name: Lint
        run: npm run lint

  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Cache and install node modules
        uses: bahmutov/npm-install@v1
      - name: Test
        run: npm run test:ci
