name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache and install node modules
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Build app
        run: NODE_ENV=test DISABLE_NEW_RELIC_IN_TESTS=true npm run build
        env:
          NEW_RELIC_LICENSE_KEY: "" # Unset or empty to disable the agent itself
          NEW_RELIC_APP_NAME: ""

      - name: Start the app
        run: |
          NODE_ENV=test DISABLE_NEW_RELIC_IN_TESTS=true npm run start &
          sleep 5
        shell: bash
        env:
          NEW_RELIC_LICENSE_KEY: "" # Unset or empty to disable the agent itself
          NEW_RELIC_APP_NAME: ""

      - name: Run Playwright tests
        run: npx playwright test
        env:
          NEW_RELIC_LICENSE_KEY: "" # Unset or empty to disable the agent itself
          NEW_RELIC_APP_NAME: ""

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
