name: Playwright Tests
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      CI: true
      COLLECTIONS_API_URL: ${{ secrets.COLLECTIONS_API_URL }}
      COLLECTIONS_API_AUTH_TOKEN: ${{ secrets.COLLECTIONS_API_AUTH_TOKEN }}
      API_URL: ${{ secrets.API_URL }}
      AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
      QA_COLLECTIONS_API_URL: ${{ secrets.QA_COLLECTIONS_API_URL }}
      QA_COLLECTIONS_API_AUTH_TOKEN: ${{ secrets.QA_COLLECTIONS_API_AUTH_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: npm
          cache-dependency-path: "package-lock.json"

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run build
        run: npm run dev & sleep 5

      - name: Run Playwright tests
        run: npx playwright test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() && failure()}}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 3
