name: Register Deployment
on:
  workflow_call:
  workflow_dispatch:
    inputs:
      cluster:
        required: true
        type: string
      service:
        required: true
        type: string
      nr-app-id:
        required: true
        type: string
      version:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  wait-then-mark:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          role-to-assume: arn:aws:iam::685731035297:role/GithubActionsDeployerRole
          aws-region: us-east-1

      - name: Wait for deployment to complete
        uses: nick-fields/retry@v3
        with:
          max_attempts: 3
          timeout_minutes: 10
          command: aws ecs wait services-stable --cluster ${{ inputs.cluster }} --services ${{ inputs.service }}

      - name: Mark deployment in New Relic
        uses: newrelic/deployment-marker-action@v2.6.2
        with:
          apiKey: ${{ secrets.NEW_RELIC_API_KEY }}
          commandType: "changeTrackingCreateEvent"
          entitySearch: "domainId='${{ inputs.nr-app-id }}'"
          version: "${{ inputs.version }}"
          category: "Deployment"
          type: "Basic"
          commit: "${{ github.sha }}"
