name: Run Swimlanes Test

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  run_swimlanes_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run Puppeteer script
        run: npm run homepageImageloadingTestProd

